### ISSUE TITLE
Update Operator for 1.0.0

### ISSUE THREAD

**Issue by gbaufake** [iter8-tools/iter8-operator#2]
- [x] Update Operator code to 1.0 (assigned @kalantar) (https://github.com/iter8-tools/iter8/issues/84)
- [x] Create Operator bundle to add into Operator Hub
- [ ] Update Kiali Iter8 resources
- [ ] Test on RH OS Community Operators

**Comment by kalantar** [comment]
I've updated it to operator-sdk 1.0.0 and modified it to install iter8 v1.0.0-rc2.
To run: `make deploy IMG=iter8/iter8-operator:0.0.1-rc2`
To install iter8 on openshift: 

```bash
oc create ns iter8
oc -n iter8 apply -f https://raw.githubusercontent.com/iter8-tools/iter8-operator/master/config/samples/iter8-redhat.yaml 
```

Then this tutorial should work: https://iter8.tools/tutorials/canary-openshift/

**Comment by kalantar** [comment]
The following are things to consider, perhaps before release:

- The apiGroup seems to have one more `iter8` than I expected. Not sure how to fix without regenerating things.
- We required the config to manually specify if the Istio mixer is enabled. This can/should be determined automatically
- The permissions granted in role.yaml are probably too broad
- The operator watches all namespaces, probably it should watch the same set as the service mesh operator does

**Comment by kalantar** [comment]
I updated the operator to compute if the Istio mixer is enabled or not. No longer needs to be specified.

**Comment by gbaufake** [comment]
@kalantar `iter8config-metrics` and `iter8config-notifiers` configmaps need to be created inside the operator logic when we are using the operatorhub.
